module.exports = {
    blog: [
        {
            title: 'Marine Safety Beyond Training',
            date: 2021-01-14,
            categories: ['Man-Overboard Training', 'Marine Safety'],
            tags: ['Man-Overboard Retrieval', 'Man-Overboard Training', 'Marine Safety', 'Marine Terminal Safety'],
            image: 'http://placekitten.com/200/300',
            intro: 'To ensure that marine employees are as safe as possible working on the water, water safety and man-overboard protection need to be built-in to the culture of the organization. However, studies have shown that occasional training programs are not as effective in ensuring safety. Water Safety Programs need to be demonstrated starting at the leadership level to be most effective. Making water safety part of the company culture. Pairing training with investment in water safety products and mechanisms help to make this a natural part of the culture. In a 2018 research essay written by Frank Dobbin and Alexandra Kalev in Anthropology Today, studies show that short-term changes in training programs are not as effective as they should be. Dobbin and Kalev mention, “sometimes a short-term change occurs in attitudes, but very few find a widespread change in actual behavior.” Dobbin and Kalev offer a few reasons why these programs generally don’t work as intended.',
            headings: ['Why Water Safety Training Programs Don’t Always Work', 'Water Safety Needs to Start with Leadership', 'Fighting Complacency and Building Confidence of Water Safety Training', 'A Company Dedicated Solely to Water Safety Equipment and Training'],
            paragraphs: ['First, “short-term educational interventions, in general, do not change people.” This is true for worker safety courses. Second, some researchers argue that the training activates stereotypes in people’s minds rather than eliminating them. Third, training can make people complacent, thinking that because they went through the program they’ve solved the problem. Fourth, people don’t like to be told what to think and may rebel if they feel that they’re being pressured to think a certain way. Therefore it’s imperative for a successful training program to implement a solid policy to effect change, not a “check the box” culture that is easily dismissed.', 'Emerald Marine Products has manufactured safety products for the maritime industry since 1996 and has partnered with dozens of other safety training institutions and product manufacturers. We have seen the successful implementation of safety procedures when the executive level of the company invests in product and policy creation that is used every day, not just quarterly or annually as required by some certification agencies. By instituting at the executive level it trickles into the entire company culture, making it feel intuitive and natural., When employees watch their leaders place a high value on safety and products that save lives, they will accept the reasoning behind use, training, and testing. When our ALERT Man-Overboard Alarm System is part of the employee’s gear and tested every shift, it becomes second nature that a fall overboard situation could occur, the actions to reduce the possibility of a MOB is top of mind. This solidifies the learning by the employee.', 'One of our partner companies C-Hero goes one step further in engaging employees with their MOB retrieval products. C-Hero offers an e-Training program on their products and the process of recognizing a MOB incident and the procedures to retrieve the MOB. The training instructs the employees but also provides accountability of the training, including the requirement for the employee to be video recorded and submitting that video for certification. It almost becomes a “badge of honor” that the employee has demonstrated their ability and dedication to the life-saving procedure.', 'Investment in dedicated equipment and “Practice Makes Permanent” is a thorough way of instilling a successful water safety program. When it comes to fall overboard awareness, practice, and retrieval, Emerald Marine Products offers products and partnerships that can be your one-source solution for instilling a MOB awareness/prevention safety culture. Let Emerald Marine Products guide you on safety solutions that best meet your company’s needs. Contact EMP via our Contact Us webpage or phone us at 800-426-4201. Make your safety training programs effective, long-lasting, and a constant part of your company’s culture.']
        }
    ]
}