module.exports = {
    press: [
        {
            title: 'NEW PORTABLE MOB ALARM SYSTEM HAS DIY INSTALLATION',
            date: new Date('2017-11-08'),
            image: 'https://res.cloudinary.com/dccnlakey/image/upload/v1624490111/Emerald%20Marine%20Images/cc2zjuix7uhp2k57cfea.jpg',
            alt: 'NEW PORTABLE MOB ALARM SYSTEM HAS DIY INSTALLATION',
            categories: ['Man-Overboard', 'Marine Safety'],
            content: `I knew a month into COVID-19 that work conditions would change drastically," said Robert Linder, Emerald Marine Products president. "I was already concerned about the lack of fall-overboard alarms. A reliable solution was needed that would make it incredibly fast and easy for companies to protect their employees. People are filled with uncertainty and worry; a fall overboard doesn't have to be one of those concerns.`
        },
        {
            title: 'Prepare for Dangers of Falling Into Cold Water',
            date: new Date('2017-12-20'),
            image: 'https://res.cloudinary.com/dccnlakey/image/upload/v1624489977/Emerald%20Marine%20Images/pralp90byl64hb7aq2aw.jpg',
            alt: 'NEW PORTABLE MOB ALARM SYSTEM HAS DIY INSTALLATION',
            categories: ['Marine Safety'],
            content: `Whether on deck or shoreside, frigid weather is fatiguing and increases the chance of falling, especially when restrictive clothing that hinders normal balance is worn. If someone goes overboard, the situation is compounded by cold water shock. Emerald Marine Products’ ALERT Man-Overboard System is a simple, proven solution that instantly notifies those within the immediate area. It provides rescuers the extra seconds needed to keep the fall from becoming a fatality. Water that’s only 60° is cold enough to generate muscle spasms, a gasp reflex and hyperventilation if fallen into. Sudden immersion can paralyze muscles and even cause a cardiac arrest. Unlike warm water, the MOB victim is unlikely to be able to shout or signal in any way. That’s what makes the ALERT System ideal for cold-weather workers. In its most basic form, the ALERT system is an automatic water-activated transmitter worn on a lifejacket and a receiver, typically installed in a wheelhouse or job office. When the device is submerged, it triggers the receiver’s alarm and flashing light, instantly notifying coworkers. The system can be wired to kill engines, set a chartplotter or GPS waypoint, and activate external strobes and speakers. Based off of Puget Sound in Edmonds, Washington, Emerald Marine Products understands the dangers of cold water. Its innovative man overboard life-saving products protect and provide peace of mind to countless deck and shoreside workers and their employers throughout North America. Contact Emerald Marine Products, 811 Alder St., Edmonds, WA 98020. 800-426-4201. info@emeraldmarineproducts.com; www.emeraldmarineproducts.com.`
        },
        {
            title: 'ALERT MOB System Offers Wide Range of Notification Options',
            date: new Date('2017-12-20'),
            image: 'https://res.cloudinary.com/dccnlakey/image/upload/v1624489977/Emerald%20Marine%20Images/pralp90byl64hb7aq2aw.jpg',
            alt: 'Man-Overboard alert on Rosepoint Software.',
            categories: ['Man-Overboard'],
            content: `The ability to instantly notify coworkers that someone has fallen into the water often means the difference between an immediate recovery and a search-and-rescue effort. Ideal for workboats, oil and gas platforms, shoreside workers, and coastal and bluewater recreational boaters, Emerald Marine Products’ ALERT Man-Overboard (MOB) Alarm System™ not only immediately alerts the vessel of the fall overboard, but has the capability to trigger a diverse range of alarms and notification tools. Unlike other MOB devices that limit how notifications can be configured, owners of the ALERT System routinely connect external speakers and strobes and wire it to kill engines. By leveraging the industry standard NMEA 0183 communication protocol, however, the system has almost unlimited ways it can be set up to notify. End users and technology partners continually develop unique approaches to utilize this adaptability. A harbor shifting, fleeting and mooring company on the Ohio, Alleghany and Monongahela Rivers, for example, wired its ALERT receivers to SECO-LARM automatic voice dialers. If a transmitter is activated, the system calls land-based managers and supervisors with a pre-recorded message that includes the location. This ensures that the important step of calling 911 isn’t overlooked while others are focused on rescuing the MOB. The ALERT System will also set a waypoint in a compatible GPS or chartplotter when a transmitter is activated. Rose Point ECS™ navigation software is on 275 fleets in North America alone and enjoys a 90% market share in the commercial marine sector. “Emerald Marine Products engineers developed an enhanced feature that automatically puts an icon on the screen when the transmitter is activated,” said Jeff Hummel, Rose Point Navigation Software director of sales and marketing. “Users then have the option to activate the waypoint or not, to avoid removing critical navigation.” The company’s website is www.rosepoint.com. Built into the ALERT418® receiver is a 95 dB alarm, flashing red faceplate lamp, and screen that displays the transmitter’s unique ID to help identify the person and overboard event’s lat/long coordinates to easily broadcast to rescue authorities. It has normally open, common and normally closed terminals to easily connect other notification devices. “The best chance for a successful MOB rescue is when crew of the vessel the person was on takes immediate action,” said Robert Linder, Emerald Marine Products president. “We built in the ability to tailor how the ALERT System notifies to meet the specific needs of unique work applications.”
            The ALERT418 Man-Overboard Receiver costs $1,899 and the Transmitter with Spray Tight Pouch, $299. A certified Intrinsically Safe (IS) option for oil and gas workers is available. Contact Emerald Marine Products, 811 Alder St., Edmonds, WA 98020. 800-426-4201. info@emeraldmarineproducts.com; www.emeraldmarineproducts.com.`
        },
        {
            title: 'Emerald Marine Launches New MOB Receiver',
            date: new Date('2017-10-16'),
            image: 'https://res.cloudinary.com/dccnlakey/image/upload/v1624489977/Emerald%20Marine%20Images/pralp90byl64hb7aq2aw.jpg',
            alt: 'Man-Overboard alert on Rosepoint Software.',
            categories: ['Man-Overboard'],
            content: `Emerald Marine Products announces a significant advancement in MOB protection: the state-of-the-art ALERT418® Man-Overboard Receiver. Integrating fully with current and first-generation ALERT transmitters, it’s ideal for commercial applications such as workboats, gas and oil platforms, ports and marine terminals, and shoreside construction sites. The innovative device leverages the latest advancements in electronics technology, while maintaining its predecessor’s proven and enviable safety record. When an ALERT transmitter is submerged, the ALERT418 receiver instantly flashes and sounds a piercing alarm in a wheelhouse or shoreside office. It displays the transmitter’s unique ID number and signal strength, critical data when lone workers are involved, as well as battery strength. The device also shows the location of the vessel at the time of incident.
            The ALERT418 Man-Overboard Receiver interfaces with popular NMEA 0183-compliant chartplotting software, so a waypoint can automatically be set upon transmitter activation. Additionally, it can be wired to kill engines, and activate external strobes and speakers. What separates the ALERT system from AIS is its immediacy. It uses a radio signal, so there’s no satellite lag or waiting for an open channel. With a moving vessel, or river or tidal flow, an MOB victim can be swept out of sight quickly. The ALERT418 Man-Overboard Receiver provides the added seconds needed to keep a simple fall from becoming a fatality. Working on a frequency of 418 MHz, the ALERT418 receiver is FCC Part 15- and Industry Canada RSS 210-approved, so licenses aren’t required. The device features a GPS connection, DB-9 serial port and dry contacts for external alarm capabilities. It includes a 15″ flexible whip antenna and 25′ of coax cable, and mounts flush or on a bracket. Emerald Marine Products’ ALERT418® Man-Overboard Receiver is made in the USA and costs $1,899.`
        },
    ]
}