module.exports = {
    products: [
        {
            name: 'ALERT Portable Man-Overboard Alarm Stand',
            price: '500.00',
            description: 'ALERT Portable Man-Overboard Alarm Stand, combines a heavy-duty metal stand, marine-grade antenna, cable, and 110volt power converter. Purchase an ALERT Receiver and any amount of ALERT Transmitters to protect your crew and you are ready for any fall-overboard alert within seconds.',
            SKU: 'AA105',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver'],
            categories: ['Overboard Alerting Products'],
            video: 'https://www.youtube.com/watch?v=1Msntf_YgNU',
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT-Portable-DIY-Stand+AA105.jpg',
            alt: 'ALERT Portable Man-Overboard Alarm Stand',
            weight: '2 lbs',
            length: '4.75',
            width: '3.75',
            height: '5.5',
            details: '[{"heading": "Description", "content": "Protect your crew easily and affordably with our ALERT Portable Man-Overboard Alarm System ™. Combining the fastest man-overboard alerting technology of our ALERT Man-Overboard Alarm System ™ with a highly durable and portable stand, you can take ALERT Man-Overboard Alarm System almost anywhere. On the ship or dockside, your crew is protected within minutes, alerting personnel of a fall overboard situation within seconds!"}, {"heading": "Configure any ALERT Products into a Portable System", "content": "If our pre-packaged ALERT Man-Overboard Portable System (AS100) consisting of one ALERT2 Receiver and two ALERT418 Transmitters does not meet your needs, you can configure the ALERT Man-Overboard Portable Alarm System anyway you like. If you already have ALERT products and want to create a portable solution, this stand makes an easy transition to highly portable MOB alerting. Purchase the Portable Stand, then select the ALERT Man-Overboard Receiver (ALERT2 or ALERT418) that best fits your man-overboard alerting needs at your location. In addition to the Receiver, you would purchase the appropriate ALERT Man-Overboard Transmitters (ALERT2 in nylon pouch, ALERT2 in a spray-tight pouch or ALERT418 in a spray-tight pouch) that works best for protecting your employees. Intrinsically-Safe Certified Transmitters are also available in model numbers AT201 and AT202."}, {"heading": "Built Specifically For These Challenging Times", "content": "Realizing that MOB awareness is greater than ever, and the concern of having third-parties on-premise to install any electronic solution, Emerald Marine Products has packaged it’s ALERT Man-Overboard System to be easily implemented in almost any location. Simply add your existing or separately purchased ALERT Man-Overboard Receiver, attach the antenna and cable to the receiver, plug the unit to a 110volt outlet and you are ready to protect your employees. No need for extensive installation, outside contractors, or complicated programming. Watch the video to see how the unit performed on a tugboat when testing out the ALERT system. You can view the video by Clicking Here. Now is the time to protect your workers. Don’t let the concerns of COVID-19 stop you from protecting your employees from a fall overboard fatality. We know that MOB’s occur regardless of viruses. As the weather warms up and workers work harder than ever, protecting your employees provides them the confidence they need to do a job well."}, {"heading": "The ALERT Man-Overboard Portable Stand Consists of:", "content": "ALERT Portable Stand, 6 inch connection cable, 14 inch Stainless Steel Antenna, 110 Volt Power Adapter"}]'
        },
        {
            name: 'ALERT Portable, DIY Man-Overboard Alarm System',
            price: '1475.00',
            description: 'ALERT Portable, DIY Man Overboard Alarm System ™, combines ALERT2 Receiver, two ALERT418 Transmitters, heavy-duty stand, antenna, cable, and 110volt power converter. Set-up within minutes. No programming needed. No third-party installation required. You are ready for any fall-overboard alert within seconds. In addition to the internal alerting, the unit can be wired to perform engine kill or other external alerting capabilities.',
            SKU: 'AS100',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver'],
            categories: ['Overboard Alerting Products'],
            video: 'https://www.youtube.com/watch?v=1Msntf_YgNU',
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT+Portable+DIY+Man-Overboard+Alarm+System.jpg',
            alt: 'ALERT Portable, DIY Man-Overboard Alarm System',
            weight: '2 lbs',
            length: '4.75',
            width: '3.75',
            height: '5.5', 
            details: '[{"heading": "Description", "content": "Protect your crew easily and affordably with our ALERT Portable, DIY Man-Overboard Alarm System ™. Combining the fastest man-overboard alerting technology of our ALERT Man-Overboard Alarm System ™ with a highly durable and portable stand, you can take ALERT Man-Overboard Alarm System almost anywhere. On the ship or dockside, your crew is protected within minutes, alerting personnel of a fall overboard situation within seconds!"}, {"heading": "Built Specifically For These Challenging Times", "content": "People are filled with uncertainty and worry, fall overboard doesn’t have to be one of those worries. Ideal for inland and coastal waters, the self-contained system is comprised of an ALERT2 Receiver and two (2) ALERT418 compact water-activated transmitters worn on a work vest. If the deckhand falls into the water, it triggers the ALERT Receiver, which sounds a piercing alarm. It can also be wired to stop engines, set a Chartplotter waypoint, and/or into a ship-wide notification system. Realizing that the MOB awareness need is greater than ever, and the concern of having third-parties on-premise to install any electronic solution, Emerald Marine Products has packaged it’s ALERT Man-Overboard System to be easily implemented in almost any location. Simply plug the unit to a 110volt outlet or wire to a 12volt system and you are ready to protect your employees. No need for extensive installation, outside contractors, or complicated programming. Watch the video to see how the unit performed on a tugboat when testing out the ALERT system. Now is the time to protect your workers. Don’t let the concerns of COVID-19 stop you from protecting your employees from a fall overboard fatality. We know that MOB’s occur regardless of viruses. As the weather warms up and workers work harder than ever, protecting your employees provides them the confidence they need to do a job well."}, {"heading": "The ALERT Portable, DIY Man-Overboard System Consists of:", "content": "ALERT2 Receiver, Two (2) ALERT418 Transmitters in spray-tight pouch or clip to attach to inflatable Personal Flotation Device (PFD), ALERT Portable Stand, 6 inch connection cable, 14 inch Stainless Steel Antenna, 110 Volt Power Adapter"}, {"heading": "Other ALERT Portable, DIY Man-Overboard Alarm System Configurations Available:", "content": "You can configure the ALERT Portable, DIY Man-Overboard Alarm System anyway you like that works best for your company by purchasing our units separately. Purchase the Portable Stand(AA105) then select the ALERT Man-Overboard Receiver (ALERT2 or ALERT418) that best fits your man-overboard alerting needs at your location. In addition to the Receiver, you would purchase the appropriate ALERT Man-Overboard Transmitters (ALERT2 in nylon pouch, ALERT2 in a spray-tight pouch or ALERT418 in a spray-tight pouch) that works best for protecting your employees. Intrinsically-Safe Certified Transmitters are also available in model numbers AT201 and AT202."}]'
        },
        {
            name: 'ALERT418® Man-Overboard Receiver',
            price: '1899.00',
            description: 'The ALERT418® Man-Overboard Receiver is the newest addition to the ALERT Man-Overboard Alarm System.The ALERT418 Man-Overboard Receiver immediately alarms the crew and vessel of a fall-overboard situation. Upon hitting the water, the ALERT Transmitter instantly transmits to the ALERT418 Receiver on the boat, alerting the crew of a man-overboard situation. The ALERT418 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters. Leveraging the latest technology while maintaining proven commercial grade capabilities makes the ALERT418 Receiver an essential safety device for anyone on the water.',
            SKU: 'AR400',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver', 'Alert2 T', 'ALERT2 Transmitter', 'ALERT418', 'ALERT418 Transmitter', 'Man-Overboard'],
            categories: ['Overboard Alerting Products'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT418+Receiver_Tilted_1280.jpg',
            alt: 'ALERT418® Man-Overboard Receiver',
            weight: '13 oz',
            length: '6',
            width: '3.75',
            height: '1.875',
            details: '[{"heading": "Description", "content": "The ALERT418® Man-Overboard Receiver immediately alarms the crew and vessel of a man-overboard situation in seconds. In addition to the fastest man-overboard alert, you can wire for engine-kill and other external alerting functions. When the difference between life and death is three minutes, the best chance of a successful rescue is by the crew onboard. The ALERT418 Receiver is installed aboard the vessel or on land for shoreside awareness. When the ALERT418 Receiver picks up an ALERT2 or ALERT418 Transmitter signal, an internal siren sounds in the Receiver and a digital display is illuminated with important information such as the location of the vessel at the time of the incident and ID number of ALERT418 Transmitter that is transmitting (ALERT2 Transmitter does not transmit unit ID). In addition to this valuable information is a Relevant Signal Strength Indicator (RSSI) to provide a numeric reading of the strength of the ALERT Transmitter. The ALERT418 Receiver also has the ability to be wired so it can shut down the engine, mark a position on a compatible Chart Plotter, sound external alarm systems, and other options."}, {"heading": "Automatically Activated", "content": "Upon immersion in water, the ALERT Transmitter instantly sends a radio signal to the onboard ALERT418 Receiver to alarm the crew and vessel of a fall-overboard."}, {"heading": "Alerts in Seconds", "content": "When every second count, the ALERT Man-Overboard Alarm System instantaneously alarms the vessel, providing the crew the critical extra seconds needed for a successful man overboard rescue. Unlike AIS, the response of the ALERT418 Receiver is immediate. There is no lag time connecting with satellites."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat."}, {"heading": "Plot Overboard Waypoint", "content": "The ALERT418 Man-Overboard Receiver can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Sending a NMEA 0183 compliant sentence, compatible chartplotting software will display the location of the incident. The ALERT418 Receiver can be directly wired to the boat’s 12-volt wiring system or connected via an optional 110-volt power supply. "}, {"heading": "Displays Valuable Transmitter Unit Information", "content": "Unit ID number – to immediately know who fell overboard; Signal strength indicator – find the MOB quicker based on single strength of the MOB’s transmitter; Low battery indicator – easily know when a transmitter needs new batteries to ensure the crew is always prepared for a man-overboard situation. An ALERT418 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters."}, {"heading": "ALERT2 Customer Looking to Upgrade?", "content": "The ALERT418 Receiver has the same dimensions as the ALERT2 Receiver, therefore, you can easily swap out the two units. Order part number AR401 if you only need the ALERT418 Receiver, GPS antenna, and serial cable. You will then be able to use your existing ALERT antenna and coaxial cable to operate the device. If you purchased your ALERT2 Receiver within the past year you may be eligible for a product rebate towards the ALERT418 Receiver."}]'
        },
        {
            name: 'ALERT418® Man-Overboard Transmitter with Spray Tight Pouch',
            price: '299.00',
            description: 'The ALERT418® Man-Overboard Transmitter is the newest Transmitter addition to the ALERT Man-Overboard Alarm System. It is is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Leveraging the latest technology while maintaining proven commercial grade capabilities makes the ALERT418 Transmitter an essential safety device for anyone on the water. The durable Spray Tight Pouch protects the ALERT418 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT401',
            tags: ['ALERT418', 'ALERT418 Transmitter', 'Spray Tight Pouch', 'Transmitter', 'Transmitter Pouch'],
            categories: ['Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT418_Transmitter.jpg',
            video: 'https://www.youtube.com/watch?v=O5K72y2tbHA',
            alt: 'ALERT418® Man-Overboard Transmitter with Spray Tight Pouch',
            weight: '3.6 oz',
            length: '4.25',
            width: '1.5',
            height: '1', 
            details: '[{"heading": "Description", "content": "The ALERT418® Man-Overboard Transmitter is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. Upon immersion, the Transmitter instantly alerts the crew of a fall-overboard. The proprietary 418Mhz frequency allows it to be automatically activated so it doesn’t have to rely on additional equipment to be triggered. The ALERT418 Transmitter has been engineered with the latest technology, making it more efficient and easy to use. The durable Spray Tight Pouch protects the ALERT418 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence."}, {"heading": "Easy to Use and Wear", "content": "It is slightly smaller and lighter than the ALERT2 Transmitter. The ALERT418 can easily clip to a self-inflating PFD, offering comfortable MOB protection. It is water activated so the man overboard doesn’t need to do anything to trigger the alarm. The Durable Spray Tight Pouch folds over the Transmitter, making it seamless to wear. The ALERT418 Transmitter is always in an armed state, with an easy “reset” button if you need to turn the Transmitter off after activation. Now there is no need to worry if a crew member forgot to “arm the transmitter” before heading off to their watch."}, {"heading": "Quickly Locate", "content": "The unit includes 6 LED lights for illumination when water-activated, providing enhanced visibility of the fall overboard."}, {"heading": "More Efficient", "content": "The low battery indicator lets you know if the readily available CR123A lithium batteries need replacement."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat."}, {"heading": "Plot Overboard Waypoint", "content": "The ALERT Man-Overboard Alarm System can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Making it easier to home in the person that fell overboard. Ease of use, automatic, and an intelligent messaging system, makes the ALERT418 Transmitter an essential safety device for anyone on the water. The ALERT418 Transmitter is compatible with the ALERT418 and ALERT2 Receivers. ALERT418 Transmitters require an ALERT418 or ALERT2 Receiver to transmit to."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™',
            price: '274.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard.',
            SKU: 'AT101 ',
            tags: ['ALERT2 Transmitter', 'Transmitter'],
            categories: ['Overboard Alerting Products'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT2Transmitter.jpg',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75', 
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device (PFD). Upon immersion, the Transmitter instantly alerts the crew of a fall-overboard. The proprietary 418Mhz frequency allows it to be automatically activated so it doesn’t have to rely on additional equipment to be triggered."}, {"heading": "Easy to Use and Wear", "content": "The ALERT2 Transmitter easily attaches to a PFD, offering comfortable MOB protection. It is water activated so the man overboard doesn’t need to do anything to trigger the alarm."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat."}, {"heading": "Plot Overboard Waypoint", "content": "The ALERT Man-Overboard Alarm System can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Making it easier to home in the person that fell overboard. The ALERT2 Transmitter has been saving lives for over 20 years. This proven, reliable, and durable safety device is essential to protect anyone on the water. ALERT2 Transmitters require an ALERT2 Receiver or ALERT418 Receiver to transmit to."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ with Spray Tight Pouch',
            price: '289.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard. The durable Spray Tight Pouch protects the ALERT2 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT102 ',
            tags: ['ALERT2 Transmitter', 'Transmitter', 'Spray Tight Pouch', 'ALERT2'],
            categories: ['Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT2TransmitterinSTP.jpg',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ with Spray Tight Pouch',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device (PFD). Upon immersion, the Transmitter instantly alerts the crew of a fall-overboard. The proprietary 418Mhz frequency allows it to be automatically activated so it doesn’t have to rely on additional equipment to be triggered. The Durable Spray Tight Pouch protects the ALERT2 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence."}, {"heading": "Easy to Use and Wear", "content": "The ALERT2 Transmitter easily attaches to a PFD, offering comfortable MOB protectionn. It is water activated so the man overboard doesn’t need to do anything to trigger the alarm. The Durable Spray Tight Pouch folds over the Transmitter, making it seamless to wear."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat."}, {"heading": "Plot Overboard Waypoint", "content": "The ALERT Man-Overboard Alarm System can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Making it easier to home in the person that fell overboard. The ALERT2 Transmitter has been saving lives for over 20 years. This proven, reliable, and durable safety device is essential to protect anyone on the water."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Intrinsically Safe Model',
            price: '369.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard. Intrinsically Safe is a protection technique for safe operation of electrical equipment in hazardous areas. The ALERT2 Transmitter Intrinsically Safe Model is extensively used by our customers in the oil and coal industries. The transmitter is certified Class 1, Div 1, Group D.',
            SKU: 'AT201 ',
            tags: ['ALERT2 Transmitter', 'Intrinsically Safe', 'ALERT2'],
            categories: ['Overboard Alerting Products'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT2TransmitterISM.jpg',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ Intrinsically Safe Model',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device (PFD). Upon immersion, the Transmitter instantly alerts the crew of a fall-overboard. The proprietary 418Mhz frequency allows it to be automatically activated so it doesn’t have to rely on additional equipment to be triggered. The ALERT2 Man-Overboard Transmitter Intrinsically Safe Model is engineered for extra protection for safe operation of electrical equipment in hazardous areas. This model is extensively used by our customers in the oil and coal industries. The transmitter is certified Class 1, Div 1, Group D."}, {"heading": "Easy to Use and Wear", "content": "The ALERT2 Transmitter easily attaches to a PFD, offering comfortable MOB protection. It is water activated so the man overboard doesn’t need to do anything to trigger the alarm."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat."}, {"heading": "Plot Overboard Waypoint", "content": "The ALERT Man-Overboard Alarm System can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Making it easier to home in the person that fell overboard. The ALERT2 Transmitter has been saving lives for over 20 years. This proven, reliable, and durable safety device is essential to protect anyone on the water. ALERT2 Transmitters require an ALERT2 Receiver or ALERT418 Receiver to transmit to."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ IS Model with Spray Tight Pouch',
            price: '389.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard. Intrinsically Safe is a protection technique for safe operation of electrical equipment in hazardous areas. The ALERT2 Transmitter Intrinsically Safe Model is extensively used by our customers in the oil and coal industries. The transmitter is certified Class 1, Div 1, Group D. The durable Spray Tight Pouch protects the ALERT2 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT201 ',
            tags: ['ALERT2 Transmitter', 'Intrinsically Safe', 'ALERT2', 'Spray Tight Pouch', 'Transmitter'],
            categories: ['Overboard Alerting Products', 'Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT2TransmitterISMinSTP.jpg',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ IS Model with Spray Tight Pouch',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device (PFD). Upon immersion, the Transmitter instantly alerts the crew of a fall-overboard. The proprietary 418Mhz frequency allows it to be automatically activated so it doesn’t have to rely on additional equipment to be triggered. The ALERT2 Man-Overboard Transmitter Intrinsically Safe Model is engineered for extra protection for safe operation of electrical equipment in hazardous areas. This model is extensively used by our customers in the oil and coal industries. The transmitter is certified Class 1, Div 1, Group D. The Durable Spray Tight Pouch protects the ALERT2 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence."}, {"heading": "Easy to Use and Wear", "content": "The ALERT2 Transmitter easily attaches to a PFD, offering comfortable MOB protection. It is water activated so the man overboard doesn’t need to do anything to trigger the alarm. The Durable Spray Tight Pouch folds over the Transmitter, making it seamless to wear."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat.", {"heading": "Plot Overboard Waypoint", "content": "The ALERT Man-Overboard Alarm System can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Making it easier to home in the person that fell overboard. The ALERT2 Transmitter has been saving lives for over 20 years. This proven, reliable, and durable safety device is essential to protect anyone on the water. ALERT2 Transmitters require an ALERT2 Receiver or ALERT418 Receiver to transmit to."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Receiver™',
            price: '800.00',
            description: 'The ALERT2 Man-Overboard Receiver™ immediately alarms the crew and vessel of a fall-overboard situation. Upon hitting the water, the ALERT Transmitter instantly transmits to the ALERT Receiver on the boat, alerting the crew of a man-overboard situation. The ALERT2 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters.',
            SKU: 'AR100',
            tags: ['ALERT2 Receiver', 'ALERT418 Transmitter', 'Receiver', 'ALERT2', 'ALERT2 Transmitter', 'Transmitter'],
            categories: ['Overboard Alerting Products'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/ALERT2Receiverbothlightselevated.jpg',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY',
            alt: 'ALERT2 Man-Overboard Transmitter™ IS Model with Spray Tight Pouch',
            weight: '12 oz',
            length: '4',
            width: '2',
            height: '6',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Receiver™ immediately alarms the crew and vessel of a man-overboard situation. When the difference between life and death is three minutes, the best chance of a successful rescue is by the crew onboard. The ALERT2 Receiver is installed aboard the vessel. When the ALERT2 Receiver picks up an ALERT2 or ALERT418 Transmitter signal, an internal siren sounds and a red Man-Overboard light is illuminated. The ALERT2 Receiver also has the ability to be wired so it can shutdown the engine, mark a position on a compatible Chart Plotter, sound external alarm systems, and other options."}, {"heading": "Automatically Activated", "content": "Upon immersion in water, the ALERT Transmitter instantly sends a radio signal to the onboard ALERT2 Receiver to alarm the crew and vessel of a fall-overboard."}, {"heading": "Alerts in Seconds", "content": "When every second counts, the ALERT Man-Overboard Alarm System instantaneously alarms the vessel, providing the crew the critical extra seconds needed for a successful man overboard rescue. Unlike AIS, the response of the ALERT2 Receiver is immediate. There is no lag time connecting with satellites."}, {"heading": "Wired for Engine Kill", "content": "For singlehanders and solo fisherman, the ALERT Man-Overboard Alarm System can be wired to shut off the engine in the event of a fall-overboard, enabling the man overboard to get back to the boat."}, {"heading": "Plot Overboard Waypoint", "content": "The ALERT Man-Overboard Alarm System can easily connect to a compatible plotter to instantly mark the location of the fall overboard. Making it easier to home in the person that fell overboard. The ALERT2 Receiver can be directly wired to the boat’s 12-volt wiring system or connected via optional 110-volt power supply. An ALERT2 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Portable Direction Finder™',
            price: '899.00',
            description: 'The ALERT2 Man-Overboard Portable Direction Finder™ provides extra support to pilot rescue operations of a man overboard. The Portable Direction Finder homes in on the ALERT2 or ALERT418 Transmitter signal by manually sweeping the horizon while monitoring the spray tight loud speaker. This rugged handheld navigational antenna makes it easier to locate and rescue a man overboard.',
            SKU: 'AF100',
            tags: ['Receiver', 'Transmitter', 'Portable Direction Finder'],
            categories: ['Overboard Alerting Products'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/Direction-Finder.png',
            video: 'https://www.youtube.com/watch?v=7hTGM9L9El4',
            alt: 'ALERT2 Man-Overboard Portable Direction Finder™',
            weight: '2 lbs',
            length: '20',
            width: '14',
            height: '6',
            details: '[{"heading": "Description", "content": "What happens if a fall overboard occurs and even though the ALERT Receiver has alarmed the crew to the incident, the crew is unable to locate the person? The ALERT2 Man-Overboard Portable Direction Finder™ is a rugged handheld navigational antenna that makes it easier to locate and rescue a man overboard. The Portable Direction Finder homes in on the ALERT2 or ALERT418 Transmitter signal by manually sweeping the horizon while monitoring the spray tight loud speaker. The Portable Direction Finder is particularly important when visual contact is compromised due to darkness or inclement weather. The Portable Direction Finder is a must-have when your vessel or work area has night operations or requires a portable rescue operation. The ALERT2 Man-Overboard Portable Direction Finder™ works with an ALERT2 or ALERT418 Transmitter."}]'
        },
        {
            name: 'OSCAR Water Rescue Training Dummy™ Now available for direct purchase!',
            price: '749.00',
            description: 'Practice Man-Overboard training sessions with a dummy that replicates a 180 pound rescue victim. Storage weight dry is 35 pounds. Fill OSCAR with water, and OSCAR replicates an adult Man-Overboard with head and arms floating above the water. OSCAR will give your water rescue training team a realistic victim to work with, so in the event the unthinkable happens, your crew will be prepared for the rescue. You can now purchase either the Forest Green or Orange OSCAR – Water Rescue Training Dummy easily and securely using the links provided below in the Description tab.',
            SKU: 'OT100',
            tags: ['OSCAR', 'Rescue Training', 'Water Rescue Training', 'Water Rescue Training Dummy'],
            categories: ['Water Rescue Training'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/OSCAR+Water+Rescue+Training+Dummies.jpg',
            video: 'https://www.youtube.com/watch?v=grQ30xpWO_8&feature=youtu.be',
            alt: 'OSCAR Water Rescue Training Dummy™',
            weight: '30 lbs dry, 180 pounds water-filled',
            length: 'N/A',
            width: '18 in',
            height: '6 ft',
            details: '[{"heading": "Description", "content": "OSCAR is designed and built to easily simulate the most realistic man-overboard rescue training of a human being. Training rescue crews using OSCAR will ensure that they are prepared to lift and move an adult sized human out of the water."}, {"heading": "Easily Transportable", "content": "OSCAR is a man-overboard dummy used for training water rescue personnel. OSCAR is designed for easily transporting to your training location. He weighs 35 pounds dry and 180 pounds when filled with water to replicate the size and weight of an adult."}, {"heading": "Constructed for Realistic Rescue Simulation", "content": "OSCAR floats at chest level like a human. At 180 pounds, he provides a very realistic human size and weight to properly train your rescue team for the recovery of a victim out of the water and into a rescue craft."}, {"heading": "Quickly Set up and Take down Training", "content": "Before use the bladders are filled with fresh or salt water from a deck hose. After the training exercise the bladders can be drained for transport and stowage. A galvanized shackle allows easy lifting from the shoulder."}, {"heading": "Durable and Built to Last", "content": "OSCAR is manufactured from extremely tough vinyl impact bladders with stainless steel joints to withstand repetitive drops overboard from any realistic height."}]'
        },
        {
            name: 'Stowage Bag for OSCAR Water Rescue Training Dummy',
            price: '150.00',
            description: 'This durable, easy-to-carry OSCAR stowage bag makes a water rescue training dummy highly portable. The bag is made out of wire mesh material to resist the marine environment breakdown of normal materials and encases the entire OSCAR dummy so no break-down is needed. With an easy-to-carry stowage bag for your training dummy, you will be able to perform more regular and effective water rescue training sessions. The large U-Shape opening allows for easy “drop-in” loading of the entire OSCAR, no need to disassemble the unit for stowage or transport. Heavy-duty YKK zippers effortlessly encase the entire OSCAR unit inside the bag. This bag has a large center compartment for storing fill-nozzle and other useful training items. Two rubber grip handles sewn on ends allow carrying to be comfortable and stable. The nylon webbing shoulder strap makes transport of the OSCAR convenient and ergonomically safe. The bag’s wire mesh material is easy to wash.',
            SKU: 'OA101',
            tags: ['OSCAR Water Rescue Training Dummy', 'Rescue Training', 'Training Dummy'],
            categories: ['Water Rescue Training', 'Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/OSCAR+Water+Rescue+Training+Dummies.jpg',
            alt: 'Stowage Bag for OSCAR Water Rescue Training Dummy',
            weight: 'N/A',
            length: 'N/A',
            width: 'N/A',
            height: 'N/A',
            details: '[{"heading": "Description", "content": "This durable, easy-to-carry OSCAR stowage bag makes a water rescue training dummy highly portable. The bag is made out of wire mesh material to resist the marine environment breakdown of normal materials and encases the entire OSCAR dummy so no break-down is needed. With an easy-to-carry stowage bag for your training dummy, you will be able to perform more regular and effective water rescue training sessions. The large U-Shape opening allows for easy drop-in loading of the entire OSCAR, no need to disassemble the unit for stowage or transport. Heavy-duty YKK zippers effortlessly encase the entire OSCAR unit inside the bag. This bag has a large center compartment for storing fill-nozzle and other useful training items. Two rubber grip handles sewn on ends allow carrying to be comfortable and stable. The nylon webbing shoulder strap makes transport of the OSCAR convenient and ergonomically safe. The bag’s wire mesh material is easy to wash. This bag is big, bold, durable, and can take the abuse of life on the boat and on the docks."}, {"heading": "Protect your portable rescue training dummy. Free Shipping Available Now!", "content": "You can order your OSCAR Water Rescue Training Dummy Stowage Bag exclusively through us and save on Free UPS Ground Shipping!"}]'
        },
        {
            name: 'ALERT2 Man-Overboard Receiver™ Wall Power Supply',
            price: '30.00',
            description: 'The ALERT2 Man-Overboard Receiver™ Wall Power Supply provides a convenient method to wire the ALERT2 Receiver to a 110 volt outlet.',
            SKU: 'AA102',
            tags: ['ALERT2', 'ALERT2 Receiver'],
            categories: ['Overboard Alerting Products', 'Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/Powerfrontfacing.jpg',
            alt: 'ALERT2 Man-Overboard Receiver™ Wall Power Supply',
            weight: '3.4 oz',
            length: '72 in',
            width: 'N/A',
            height: 'N/A',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Receiver™ Wall Power Supply provides a convenient method to wire the ALERT2 Receiver to a 110 volt outlet. When wiring to a 12 volt power system is not possible, the converter makes it easy to plug the ALERT2 Man-Overboard Receiver into a standard 110 volt wall outlet."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Pouch',
            price: '20.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ Pouch is designed to hold the ALERT2 Transmitter to attach to the Personal Flotation Device. This standard durable nylon pouch only needs to be purchased in the event that the ALERT2 Transmitter pouch needs to be replaced.',
            SKU: 'AA101',
            tags: ['Accessories', 'Transmitter', 'Man-Overboard System'],
            categories: ['Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/TransmitterPouchside.jpg',
            video: 'https://www.youtube.com/watch?v=a8cmMlaPxhE',
            alt: 'ALERT2 Man-Overboard Transmitter™ Pouch',
            weight: '1.4 oz',
            length: '8.5',
            width: '2',
            height: 'N/A',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Transmitter™ Pouch is designed to hold the ALERT2 Transmitter to attach to the Personal Flotation Device. This standard durable nylon pouch only needs to be purchased in the event that the ALERT2 Transmitter pouch needs to be replaced."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Spray Tight Pouch',
            price: '40.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ Spray Tight Pouch protects the ALERT2 Man-Overboard Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AA103',
            tags: ['ALERT2', 'ALERT2 Transmitter', 'Spray Tight Pouch', 'Transmitter'],
            categories: ['Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/SprayTightPouch.jpg',
            alt: 'ALERT2 Man-Overboard Transmitter™ Spray Tight Pouch',
            weight: '1.75 oz',
            length: '6.75',
            width: '3.75',
            height: '3',
            details: '[{"heading": "Description", "content": "The durable Spray Tight Pouch protects the ALERT2 Man-Overboard Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence. The pouch folds completely over the ALERT2 Transmitter, making it seamless to wear. It is specifically recommended for those working in extreme water conditions, like those found on commercial fishing vessels."}]'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Replacement Batteries',
            price: '20.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ Replacement Batteries are a set of two (2) 3.6 volt lithium batteries used for replacement of batteries in ALERT2 Transmitter or ALERT2 Portable Direction Finder. PLEASE NOTE: These batteries can not be shipped outside of United States.',
            SKU: 'AA100',
            tags: ['ALERT2', 'ALERT2 Transmitter', 'Batteries', 'Portable Direction Finder', 'Transmitter'],
            categories: ['Accessories'],
            image: 'https://user-images-72a4be97-dc8f-499e-8fe0-ec69030da4f5.s3.us-west-2.amazonaws.com/Batteries.jpg',
            video: 'https://www.youtube.com/watch?v=I_tM94CLTCM&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ Replacement Batteries',
            weight: 'N/A',
            length: 'N/A',
            width: 'N/A',
            height: 'N/A',
            details: '[{"heading": "Description", "content": "The ALERT2 Man-Overboard Transmitter™ Replacement Batteries are a set of two (2) 3.6 volt lithium batteries used for replacement of batteries in ALERT2 Transmitter or ALERT2 Portable Direction Finder."}]'
        }
    ]
}