module.exports = {
    products: [
        {
            name: 'ALERT Portable Man-Overboard Alarm Stand',
            price: '500.00',
            description: 'ALERT Portable Man-Overboard Alarm Stand, combines a heavy-duty metal stand, marine-grade antenna, cable, and 110volt power converter. Purchase an ALERT Receiver and any amount of ALERT Transmitters to protect your crew and you are ready for any fall-overboard alert within seconds.',
            SKU: 'AA105',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver'],
            categories: ['Man-Overboard System', 'Receiver', 'Transmitter'],
            video: 'https://www.youtube.com/watch?v=1Msntf_YgNU',
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT Portable Man-Overboard Alarm Stand',
            weight: '2',
            length: '4.75',
            width: '3.75',
            height: '5.5'
        },
        {
            name: 'ALERT Portable, DIY Man-Overboard Alarm System',
            price: '1475.00',
            description: 'ALERT Portable, DIY Man Overboard Alarm System ™, combines ALERT2 Receiver, two ALERT418 Transmitters, heavy-duty stand, antenna, cable, and 110volt power converter. Set-up within minutes. No programming needed. No third-party installation required. You are ready for any fall-overboard alert within seconds. In addition to the internal alerting, the unit can be wired to perform engine kill or other external alerting capabilities.',
            SKU: 'AS100',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver'],
            categories: ['Man-Overboard System', 'Receiver', 'Transmitter'],
            video: 'https://www.youtube.com/watch?v=1Msntf_YgNU',
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT Portable, DIY Man-Overboard Alarm System',
            weight: '2',
            length: '4.75',
            width: '3.75',
            height: '5.5'
        },
        {
            name: 'ALERT418® Man-Overboard Receiver',
            price: '1899.00',
            description: 'The ALERT418® Man-Overboard Receiver is the newest addition to the ALERT Man-Overboard Alarm System.The ALERT418 Man-Overboard Receiver immediately alarms the crew and vessel of a fall-overboard situation. Upon hitting the water, the ALERT Transmitter instantly transmits to the ALERT418 Receiver on the boat, alerting the crew of a man-overboard situation. The ALERT418 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters. Leveraging the latest technology while maintaining proven commercial grade capabilities makes the ALERT418 Receiver an essential safety device for anyone on the water.',
            SKU: 'AR400',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver', 'Alert2 T', 'ALERT2 Transmitter', 'ALERT418', 'ALERT418 Transmitter', 'Man-Overboard'],
            categories: ['Man-Overboard System', 'Receiver'],
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT418® Man-Overboard Receiver',
            weight: '13 oz',
            length: '6',
            width: '3.75',
            height: '1.875'
        },
        {
            name: 'ALERT418® Man-Overboard Transmitter with Spray Tight Pouch',
            price: '299.00',
            description: 'The ALERT418® Man-Overboard Transmitter is the newest Transmitter addition to the ALERT Man-Overboard Alarm System. It is is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Leveraging the latest technology while maintaining proven commercial grade capabilities makes the ALERT418 Transmitter an essential safety device for anyone on the water. The durable Spray Tight Pouch protects the ALERT418 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT401',
            tags: ['ALERT418', 'ALERT418 Transmitter', 'Spray Tight Pouch', 'Transmitter', 'Transmitter Pouch'],
            categories: ['Man-Overboard System', 'Transmitter'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=O5K72y2tbHA',
            alt: 'ALERT418® Man-Overboard Transmitter with Spray Tight Pouch',
            weight: '3.6 oz',
            length: '4.25',
            width: '1.5',
            height: '1'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter',
            price: '274.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard.',
            SKU: 'AT101 ',
            tags: ['ALERT2 Transmitter', 'Transmitter'],
            categories: ['Man-Overboard System', 'Transmitter'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter',
            weight: '3.6 oz',
            length: '4.25',
            width: '1.5',
            height: '1'
        },
    ]
}