module.exports = {
    products: [
        {
            name: 'ALERT Portable Man-Overboard Alarm Stand',
            price: '500.00',
            description: 'ALERT Portable Man-Overboard Alarm Stand, combines a heavy-duty metal stand, marine-grade antenna, cable, and 110volt power converter. Purchase an ALERT Receiver and any amount of ALERT Transmitters to protect your crew and you are ready for any fall-overboard alert within seconds.',
            SKU: 'AA105',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver'],
            categories: ['Overboard Alerting Products'],
            video: 'https://www.youtube.com/watch?v=1Msntf_YgNU',
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT Portable Man-Overboard Alarm Stand',
            weight: '2 lbs',
            length: '4.75',
            width: '3.75',
            height: '5.5'
        },
        {
            name: 'ALERT Portable, DIY Man-Overboard Alarm System',
            price: '1475.00',
            description: 'ALERT Portable, DIY Man Overboard Alarm System ™, combines ALERT2 Receiver, two ALERT418 Transmitters, heavy-duty stand, antenna, cable, and 110volt power converter. Set-up within minutes. No programming needed. No third-party installation required. You are ready for any fall-overboard alert within seconds. In addition to the internal alerting, the unit can be wired to perform engine kill or other external alerting capabilities.',
            SKU: 'AS100',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver'],
            categories: ['Overboard Alerting Products'],
            video: 'https://www.youtube.com/watch?v=1Msntf_YgNU',
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT Portable, DIY Man-Overboard Alarm System',
            weight: '2 lbs',
            length: '4.75',
            width: '3.75',
            height: '5.5'
        },
        {
            name: 'ALERT418® Man-Overboard Receiver',
            price: '1899.00',
            description: 'The ALERT418® Man-Overboard Receiver is the newest addition to the ALERT Man-Overboard Alarm System.The ALERT418 Man-Overboard Receiver immediately alarms the crew and vessel of a fall-overboard situation. Upon hitting the water, the ALERT Transmitter instantly transmits to the ALERT418 Receiver on the boat, alerting the crew of a man-overboard situation. The ALERT418 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters. Leveraging the latest technology while maintaining proven commercial grade capabilities makes the ALERT418 Receiver an essential safety device for anyone on the water.',
            SKU: 'AR400',
            tags: ['ALERT Man-Overboard Alarm System', 'ALERT2 Receiver', 'ALERT418 Receiver', 'Alert2 T', 'ALERT2 Transmitter', 'ALERT418', 'ALERT418 Transmitter', 'Man-Overboard'],
            categories: ['Overboard Alerting Products'],
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT418® Man-Overboard Receiver',
            weight: '13 oz',
            length: '6',
            width: '3.75',
            height: '1.875'
        },
        {
            name: 'ALERT418® Man-Overboard Transmitter with Spray Tight Pouch',
            price: '299.00',
            description: 'The ALERT418® Man-Overboard Transmitter is the newest Transmitter addition to the ALERT Man-Overboard Alarm System. It is is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Leveraging the latest technology while maintaining proven commercial grade capabilities makes the ALERT418 Transmitter an essential safety device for anyone on the water. The durable Spray Tight Pouch protects the ALERT418 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT401',
            tags: ['ALERT418', 'ALERT418 Transmitter', 'Spray Tight Pouch', 'Transmitter', 'Transmitter Pouch'],
            categories: ['Accessories'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=O5K72y2tbHA',
            alt: 'ALERT418® Man-Overboard Transmitter with Spray Tight Pouch',
            weight: '3.6 oz',
            length: '4.25',
            width: '1.5',
            height: '1'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™',
            price: '274.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard.',
            SKU: 'AT101 ',
            tags: ['ALERT2 Transmitter', 'Transmitter'],
            categories: ['Overboard Alerting Products'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ with Spray Tight Pouch',
            price: '289.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard. The durable Spray Tight Pouch protects the ALERT2 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT102 ',
            tags: ['ALERT2 Transmitter', 'Transmitter', 'Spray Tight Pouch', 'ALERT2'],
            categories: ['Accessories'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ with Spray Tight Pouch',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Intrinsically Safe Model',
            price: '369.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard. Intrinsically Safe is a protection technique for safe operation of electrical equipment in hazardous areas. The ALERT2 Transmitter Intrinsically Safe Model is extensively used by our customers in the oil and coal industries. The transmitter is certified Class 1, Div 1, Group D.',
            SKU: 'AT201 ',
            tags: ['ALERT2 Transmitter', 'Intrinsically Safe', 'ALERT2'],
            categories: ['Overboard Alerting Products'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ Intrinsically Safe Model',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ IS Model with Spray Tight Pouch',
            price: '389.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ is a lightweight water-activated Transmitter that easily attaches to a Personal Flotation Device. It is automatically activated upon hitting water, instantly alerting the crew of a fall-overboard. Before the Fall Overboard comes up for his or her first breath of air, the ALERT2 Transmitter is already alarming the crew on-board that there is a fall overboard. Intrinsically Safe is a protection technique for safe operation of electrical equipment in hazardous areas. The ALERT2 Transmitter Intrinsically Safe Model is extensively used by our customers in the oil and coal industries. The transmitter is certified Class 1, Div 1, Group D. The durable Spray Tight Pouch protects the ALERT2 Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AT201 ',
            tags: ['ALERT2 Transmitter', 'Intrinsically Safe', 'ALERT2', 'Spray Tight Pouch', 'Transmitter'],
            categories: ['Overboard Alerting Products', 'Accessories'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ IS Model with Spray Tight Pouch',
            weight: '4 oz',
            length: '4.5',
            width: '1.5',
            height: '.75'
        },
        {
            name: 'ALERT2 Man-Overboard Receiver™',
            price: '800.00',
            description: 'The ALERT2 Man-Overboard Receiver™ immediately alarms the crew and vessel of a fall-overboard situation. Upon hitting the water, the ALERT Transmitter instantly transmits to the ALERT Receiver on the boat, alerting the crew of a man-overboard situation. The ALERT2 Receiver supports an unlimited number of ALERT2 or ALERT418 Transmitters.',
            SKU: 'AR100',
            tags: ['ALERT2 Receiver', 'ALERT418 Transmitter', 'Receiver', 'ALERT2', 'ALERT2 Transmitter', 'Transmitter'],
            categories: ['Overboard Alerting Products'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=Bnh3caPYvhY',
            alt: 'ALERT2 Man-Overboard Transmitter™ IS Model with Spray Tight Pouch',
            weight: '12 oz',
            length: '4',
            width: '2',
            height: '6'
        },
        {
            name: 'ALERT2 Man-Overboard Portable Direction Finder™',
            price: '899.00',
            description: 'The ALERT2 Man-Overboard Portable Direction Finder™ provides extra support to pilot rescue operations of a man overboard. The Portable Direction Finder homes in on the ALERT2 or ALERT418 Transmitter signal by manually sweeping the horizon while monitoring the spray tight loud speaker. This rugged handheld navigational antenna makes it easier to locate and rescue a man overboard.',
            SKU: 'AF100',
            tags: ['Receiver', 'Transmitter', 'Portable Direction Finder'],
            categories: ['Overboard Alerting Products'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=7hTGM9L9El4',
            alt: 'ALERT2 Man-Overboard Portable Direction Finder™',
            weight: '2 lbs',
            length: '20',
            width: '14',
            height: '6'
        },
        {
            name: 'OSCAR Water Rescue Training Dummy™ Now available for direct purchase!',
            price: '749.00',
            description: 'Practice Man-Overboard training sessions with a dummy that replicates a 180 pound rescue victim. Storage weight dry is 35 pounds. Fill OSCAR with water, and OSCAR replicates an adult Man-Overboard with head and arms floating above the water. OSCAR will give your water rescue training team a realistic victim to work with, so in the event the unthinkable happens, your crew will be prepared for the rescue. You can now purchase either the Forest Green or Orange OSCAR – Water Rescue Training Dummy easily and securely using the links provided below in the Description tab.',
            SKU: 'OT100',
            tags: ['OSCAR', 'Rescue Training', 'Water Rescue Training', 'Water Rescue Training Dummy'],
            categories: ['Water Rescue Training'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=grQ30xpWO_8&feature=youtu.be',
            alt: 'OSCAR Water Rescue Training Dummy™',
            weight: '30 lbs dry, 180 pounds water-filled',
            length: 'N/A',
            width: '18 in',
            height: '6 ft'
        },
        {
            name: 'Stowage Bag for OSCAR Water Rescue Training Dummy',
            price: '150.00',
            description: 'This durable, easy-to-carry OSCAR stowage bag makes a water rescue training dummy highly portable. The bag is made out of wire mesh material to resist the marine environment breakdown of normal materials and encases the entire OSCAR dummy so no break-down is needed. With an easy-to-carry stowage bag for your training dummy, you will be able to perform more regular and effective water rescue training sessions. The large U-Shape opening allows for easy “drop-in” loading of the entire OSCAR, no need to disassemble the unit for stowage or transport. Heavy-duty YKK zippers effortlessly encase the entire OSCAR unit inside the bag. This bag has a large center compartment for storing fill-nozzle and other useful training items. Two rubber grip handles sewn on ends allow carrying to be comfortable and stable. The nylon webbing shoulder strap makes transport of the OSCAR convenient and ergonomically safe. The bag’s wire mesh material is easy to wash.',
            SKU: 'OA101',
            tags: ['OSCAR Water Rescue Training Dummy', 'Rescue Training', 'Training Dummy'],
            categories: ['Water Rescue Training', 'Accessories'],
            image: 'http://placekitten.com/200/300',
            alt: 'Stowage Bag for OSCAR Water Rescue Training Dummy',
            weight: 'N/A',
            length: 'N/A',
            width: 'N/A',
            height: 'N/A'
        },
        {
            name: 'ALERT2 Man-Overboard Receiver™ Wall Power Supply',
            price: '30.00',
            description: 'The ALERT2 Man-Overboard Receiver™ Wall Power Supply provides a convenient method to wire the ALERT2 Receiver to a 110 volt outlet.',
            SKU: 'AA102',
            tags: ['ALERT2', 'ALERT2 Receiver'],
            categories: ['Overboard Alerting Products', 'Accessories'],
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT2 Man-Overboard Receiver™ Wall Power Supply',
            weight: '3.4 oz',
            length: '72 in',
            width: 'N/A',
            height: 'N/A'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Pouch',
            price: '20.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ Pouch is designed to hold the ALERT2 Transmitter to attach to the Personal Flotation Device. This standard durable nylon pouch only needs to be purchased in the event that the ALERT2 Transmitter pouch needs to be replaced.',
            SKU: 'AA101',
            tags: ['Accessories', 'Transmitter', 'Man-Overboard System'],
            categories: ['Accessories'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=a8cmMlaPxhE',
            alt: 'ALERT2 Man-Overboard Transmitter™ Pouch',
            weight: '1.4 oz',
            length: '8.5',
            width: '2',
            height: 'N/A'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Spray Tight Pouch',
            price: '40.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ Spray Tight Pouch protects the ALERT2 Man-Overboard Transmitter from accidentally activating due to extreme water conditions onboard, while enabling it to activate when immersed in water due to a fall-overboard occurrence.',
            SKU: 'AA103',
            tags: ['ALERT2', 'ALERT2 Transmitter', 'Spray Tight Pouch', 'Transmitter'],
            categories: ['Accessories'],
            image: 'http://placekitten.com/200/300',
            alt: 'ALERT2 Man-Overboard Transmitter™ Spray Tight Pouch',
            weight: '1.75 oz',
            length: '6.75',
            width: '3.75',
            height: '3'
        },
        {
            name: 'ALERT2 Man-Overboard Transmitter™ Replacement Batteries',
            price: '20.00',
            description: 'The ALERT2 Man-Overboard Transmitter™ Replacement Batteries are a set of two (2) 3.6 volt lithium batteries used for replacement of batteries in ALERT2 Transmitter or ALERT2 Portable Direction Finder. PLEASE NOTE: These batteries can not be shipped outside of United States.',
            SKU: 'AA100',
            tags: ['ALERT2', 'ALERT2 Transmitter', 'Batteries', 'Portable Direction Finder', 'Transmitter'],
            categories: ['Accessories'],
            image: 'http://placekitten.com/200/300',
            video: 'https://www.youtube.com/watch?v=I_tM94CLTCM&feature=youtu.be',
            alt: 'ALERT2 Man-Overboard Transmitter™ Replacement Batteries',
            weight: 'N/A',
            length: 'N/A',
            width: 'N/A',
            height: 'N/A'
        }
    ]
}